### PR TITLE
Fix ^M in the end of line

### LINKED ISSUE #1: git-splits contains carriage-return characters
which leads to arcane errors like

fatal: 'splits' appears to be a git command, but we were not
able to execute it. Maybe git-splits is broken?

### PR DESCRIPTION
**Pull request by evjak**
close #1

### CODE REVIEW

**Comment by evjak** [comment]
Hi, @mhaberler ! If you want, you can review my pull request :)

**Comment by evjak** [comment]
@mhaberler i am just re save this file via vim

**Comment by amenk** [comment]
I think he just replaced the line endings, that is why it looks like a full replacement. The current line endings cause problems under Linux.

**Comment by ajdruff** [comment]
Thank you for the PR. ^M characters didn't show up in vscode even with special characters turned on. I had to run `cat -v` to  see them. Removed them with dos2unix. This will be fixed with  next release.

**Pull request closed without merging**
